remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Vy Huynh Capstone Project ePortfolio 
description: ![Languages](https://img.shields.io/badge/Languages-Python%2C%20JavaScript-blue)
